### ISSUE TITLE
RuntimeError: Expected object of backend CUDA but got backend CPU for argument #2 'other'

### ISSUE THREAD

**Issue by WZheyi** [tobiascz/TeCNO#1]
Traceback (most recent call last):
  File "train.py", line 173, in <module>
    train(hparams, ModuleClass, ModelClass, DatasetClass, loggers)
  File "train.py", line 102, in train
    trainer.fit(module)
  File "/home/data3/wzy/anaconda3/envs/mtcnn/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 1003, in fit
    results = self.single_gpu_train(model)
  File "/home/data3/wzy/anaconda3/envs/mtcnn/lib/python3.6/site-packages/pytorch_lightning/trainer/distrib_parts.py", line 186, in single_gpu_train
    results = self.run_pretrain_routine(model)
  File "/home/data3/wzy/anaconda3/envs/mtcnn/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 1213, in run_pretrain_routine
    self.train()
  File "/home/data3/wzy/anaconda3/envs/mtcnn/lib/python3.6/site-packages/pytorch_lightning/trainer/training_loop.py", line 370, in train
    self.run_training_epoch()
  File "/home/data3/wzy/anaconda3/envs/mtcnn/lib/python3.6/site-packages/pytorch_lightning/trainer/training_loop.py", line 470, in run_training_epoch
    self.run_evaluation(test_mode=False)
  File "/home/data3/wzy/anaconda3/envs/mtcnn/lib/python3.6/site-packages/pytorch_lightning/trainer/evaluation_loop.py", line 430, in run_evaluation
    self.on_validation_end()
  File "/home/data3/wzy/anaconda3/envs/mtcnn/lib/python3.6/site-packages/pytorch_lightning/trainer/callback_hook.py", line 112, in on_validation_end
    callback.on_validation_end(self, self.get_model())
  File "/home/data3/wzy/anaconda3/envs/mtcnn/lib/python3.6/site-packages/pytorch_lightning/callbacks/early_stopping.py", line 141, in on_validation_end
    self._run_early_stopping_check(trainer, pl_module)
  File "/home/data3/wzy/anaconda3/envs/mtcnn/lib/python3.6/site-packages/pytorch_lightning/callbacks/early_stopping.py", line 155, in _run_early_stopping_check
    if self.monitor_op(current - self.min_delta, self.best_score):
RuntimeError: Expected object of backend CUDA but got backend CPU for argument #2 'other'

How can I solve this problem? Thank you very much !

**Comment by tobiascz** [comment]
Are you running this with a GPU or only CPU?

**Comment by wr0112358** [comment]
I am getting the exact same error. Tried running with 1 gpu and without gpu.
Also tried changing the Trainer parameter gpus and auto_select_gpus to no avail.

**Comment by saiprabhat** [comment]
the author @tobiascz has made changes to the .yml config file and in train.py for the `gpu` options. 

I tested it locally and the code runs fine now. @wr0112358 and @WZheyi could you please test and confirm so that the issue can be closed?

**Comment by tobiascz** [comment]
Hey @wr0112358 I will close this error as I changed the code quiet a bit. Please try the new version and tell me if you have any further questions. Thanks for the interest in our work
