### ISSUE TITLE
Package versions

### ISSUE THREAD

**Issue by kubicndmr** [tobiascz/TeCNO#12]
Hello, 

Thank you for sharing your code. With current package versions, I couldn't run the code. Could you chech the versions? 

I used pytorch-lightning=0.8.5 but self.log is not defined in that version. 
`AttributeError: 'FeatureExtraction' object has no attribute 'log'`

Then I tried also with version 1.0.6 (because it is mentioned in one of the issues) and i got this error 

`  File "/home/kubi/Desktop/TeCNO/train.py", line 57, in train
    trainer = Trainer(
  File "/home/kubi/miniconda3/envs/tecnoEnv/lib/python3.9/site-packages/pytorch_lightning/trainer/connectors/env_vars_connector.py", line 41, in overwrite_by_env_vars
    return fn(self, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'log_save_interval'`

**Comment by leonmayer** [comment]
I got it to work by installing pytorch-lightning=1.1.8 and changing `pl.metrics.Fbeta` to `pl.metrics.FBeta` in `feature_extraction.py`.

**Comment by Fan2022HNU** [comment]
I install pytorch-lightning==0.8.5, and changing pl.metrics.Fbeta to pl.metrics.FBeta in feature_extraction.py. A error happen here.
pl.metrics.FBeta(num_classes=7, multilabel=True)
Traceback (most recent call last):
  File "/home/fwp/.pycharm_helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
TypeError: __init__() got an unexpected keyword argument 'multilabel'
